### ISSUE TITLE
Compilation error when referencing ClosedXML.Extensions.Mvc 

### ISSUE THREAD

**Issue by vkirienko** [ClosedXML/ClosedXML.Extensions.Mvc#5]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.96.0

**What is the current behavior?**

Application references ClosedXML 0.96.0 as well ClosedXML.Extensions.Mvc 0.3.0. After going from 0.95.4 ClosedXML version getting error below calling Deliver method from ClosedXML.Extensions.Mvc.

error CS0012: The type 'XLWorkbook' is defined in an assembly that is not referenced. You must add a reference to assembly 'ClosedXML, Version=0.93.0.0, Culture=neutral, PublicKeyToken=null'.

**What is the expected behavior or new feature?**

No errors.

**Is this a regression from the previous version?**

TBD

## Reproducibility

References ClosedXML 0.96.0 as well ClosedXML.Extensions.Mvc 0.3.0 and try to compile code below.

**Code to reproduce problem:**
```c#
using ClosedXML;
using ClosedXML.Excel;
using ClosedXML.Extensions;

void Main()
{
    using var wb = new XLWorkbook("abc.xlsx", XLEventTracking.Disabled);
    var res = wb.Deliver("xyz.xlsx");
}
```

**Comment by igitur** [comment]
Hi @augustoproiete . Since you [advocated hard](https://github.com/ClosedXML/ClosedXML/issues/1547) for signing ClosedXML, would you mind helping out here? What is the recommended approach for this downstream .NET Core library? Should this now also be signed?

**Comment by augustoproiete** [comment]
Hey @igitur, what's happening here is that `ClosedXML.Extensions.Mvc` references the unsigned version of the ClosedXML assembly, and now that the assembly is signed, its identity changed, so the .NET runtime can't find it anymore (expected).

So **at a minimum**, you'll need to release a new version of `ClosedXML.Extensions.Mvc` referencing the ClosedXML v0.96.0 package - this will resolve the compilation error.

Signing `ClosedXML.Extensions.Mvc` is not required for resolving the issue, but I would recommend signing it as well as a good practice, for pretty much the [same reasons I outlined for the core ClosedXML library](https://github.com/ClosedXML/ClosedXML/issues/1547).

**Comment by igitur** [comment]
Thanks @augustoproiete

@vkirienko I've published version 0.4.0 of this library, which is now signed. Please test this and let me know if it solves your issue.

**Comment by vkirienko** [comment]
Hi, Is there a Nuget package for 0.4.0? I don't see it.

**Comment by igitur** [comment]
Sorry, it was unlisted. Try now... https://www.nuget.org/packages/ClosedXML.Extensions.Mvc/0.4.0/

**Comment by vkirienko** [comment]
It is working now. Thank you!

**Comment by artemsnezhny** [comment]
It seems like the same error appeared with the [ClosedXML 0.103.0-beta](https://github.com/ClosedXML/ClosedXML/releases/tag/0.103.0-beta) release
```
The type 'XLWorkbook' is defined in an assembly that is not referenced. You must add a reference to assembly 'ClosedXML, Version=0.96.0.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b'.
```

**Comment by Sharparam** [comment]
Chiming in to add that this happened when we upgraded from ClosedXML 0.102.2 to 0.104.1.

We just copied the extension code we needed since it's so few lines anyway and removed the extension package from dependencies, but a bit of a bummer really.

**Comment by igitur** [comment]
Try https://www.nuget.org/packages/ClosedXML.Extensions.Mvc/0.5.0
